# Copyright 2018 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: Pantheon
site_url: https://docs.pantheon.pegasys.tech/
site_description: Pantheon Java Ethereum client documentation.
site_author: Pantheon community
copyright: Pantheon and its documentation are licensed under Apache 2.0 license /
  This <a href="https://readthedocs.org/">Readthedocs.org</a> documentation is maintained with love by <a href="https://pegasys.tech/">PegaSys</a>.

#extra project info and template customisation
extra:
  doc_site_edit_url: https://github.com/PegaSysEng/doc.pantheon/
  versions:
    pantheon_stable: &pantheon_stable_version 1.2.0
    quickstart: *pantheon_stable_version
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading Pantheon development version documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the version box at screen bottom.'
  support:
    gitter: https://gitter.im/PegaSysEng/pantheon
    email: support@pegasys.tech
    pegasys_website: https://pegasys.tech/
    issues: https://pegasys1.atlassian.net/secure/Dashboard.jspa?selectPageId=10000
  google:
    site_verification: 'za1cLzyS6LXDGO-pMzvfQdYTZ0Zc67uZtY0asA4YXZ0'
    tag_manager: 'GTM-5B7N84J'
  search:
    language: 'en'
    tokenizer: '[\s]+'

# Repository
repo_name: PegaSysEng/pantheon
repo_url: https://github.com/PegaSysEng/pantheon/

theme:
    name: material
    custom_dir: docs/custom_theme
    palette:
        primary: blue-grey
        accent: teal
    favicon: favicon.ico
    logo:
      icon: account_balance
nav:
    - Tutorials:
        - Private Network Quickstart: Tutorials/Private-Network-Quickstart.md
        - Private Network Quickstart for Private Transactions: Tutorials/Privacy-Quickstart.md
        - Private Network Quickstart On Azure: Tutorials/Azure/Azure-Private-Network-Quickstart.md
        - Create a Private Network using Ethash (Pow): Tutorials/Create-Private-Network.md
        - Create a Private Network using Clique (PoA): Tutorials/Create-Private-Clique-Network.md
        - Create a Private Network using IBFT 2.0 (PoA): Tutorials/Create-IBFT-Network.md
        - Create a Permissioned Network: Tutorials/Create-Permissioned-Network.md
        - Create a Privacy-Enabled Network: Tutorials/Configuring-Privacy.md
        - Use web3.js-eea Multinode Example: Tutorials/eeajs-Multinode-example.md
        - Get Started with Onchain Permissioning: Tutorials/Getting-Started-Onchain-Permissioning.md
    - How To:
        - Get Started with Pantheon:
            - Install Binary Distribution: HowTo/Get-Started/Install-Binaries.md
            - Build from Source: HowTo/Get-Started/Build-From-Source.md
            - Start Pantheon: HowTo/Get-Started/Starting-Pantheon.md
            - Run Pantheon from Docker Image: HowTo/Get-Started/Run-Docker-Image.md
            - Migrate from pre v1.2 Docker Image: HowTo/Get-Started/Migration-Docker.md
        - Use:
            - Pantheon APIs:
              - Access Pantheon APIs: HowTo/Use/Pantheon-APIs/Pantheon-API.md
              - Use JSON-RPC API over HTTP or WebSockets: HowTo/Use/Pantheon-APIs/Using-JSON-RPC-API.md
              - Use RPC Pub/Sub API over WebSockets: HowTo/Use/Pantheon-APIs/RPC-PubSub.md
              - Use GraphQL over HTTP: HowTo/Use/Pantheon-APIs/GraphQL.md
              - Authenticate JSON-RPC Requests: HowTo/Use/Pantheon-APIs/Authentication.md
            - Consensus Protocols:
              - Use Clique: HowTo/Use/Consensus-Protocols/Clique.md
              - Use IBFT 2.0: HowTo/Use/Consensus-Protocols/IBFT.md
              - Connect to Quorum IBFT 1.0 Network: HowTo/Use/Consensus-Protocols/QuorumIBFT.md
            - Privacy API Methods:
              - Use EEA-compliant Privacy: HowTo/Use/Privacy-API-Methods/EEA-Compliant.md
              - Use Pantheon-extended Privacy: HowTo/Use/Privacy-API-Methods/Pantheon-Privacy.md
              - Create and Manage Privacy Groups: HowTo/Use/Privacy-API-Methods/Create-Manage-Privacy-Groups.md
              - Access Private and Privacy Marker Transactions: HowTo/Use/Privacy-API-Methods/Access-Private-Transactions.md
            - Permissioning:
              - Use Local Permissioning: HowTo/Use/Permissioning/Local-Permissioning.md
              - Update Onchain Permissioning Whitelists: HowTo/Use/Permissioning/Updating-Whitelists.md
            - Client Libraries:
              - Use the web3.js-eea Client Library: HowTo/Use/Client-Libraries/eeajs.md
            - Filters:
              - Access Logs Using JSON-RPC API: HowTo/Use/Filters/Accessing-Logs-Using-JSON-RPC.md
        - Configure Pantheon:
           - Specify Options in a Configuration File: HowTo/Configure-Pantheon/Using-Configuration-File.md
           - Configure a Free Gas Network: HowTo/Configure-Pantheon/FreeGas.md
           - Predeploy a Contract in the Genesis File: HowTo/Configure-Pantheon/Contracts-in-Genesis.md
           - Pass JVM Options: HowTo/Configure-Pantheon/Passing-JVM-Options.md
        - Send Transactions:
           - Use Wallets for Key Management: HowTo/Send-Transactions/Account-Management.md
           - Create and Send Transactions: HowTo/Send-Transactions/Transactions.md
           - Create and Send Private Transactions: HowTo/Send-Transactions/Creating-Sending-Private-Transactions.md
           - Include Revert Reason in Transaction Receipts: HowTo/Send-Transactions/Revert-Reason.md
        - Deploy for Production:
          - Use Ansible to Deploy Pantheon: HowTo/Deploy/Ansible.md
          - Use Prometheus for Monitoring: HowTo/Deploy/Monitoring-Performance.md
          - Use Alethio Lite Explorer: HowTo/Deploy/Lite-Block-Explorer.md
          - Use Alethio EthStats Lite Network Monitor: HowTo/Deploy/Lite-Network-Monitor.md
          - Configure High Availability of APIs: HowTo/Deploy/High-Availability.md
          - Deploy Permissioning Management Dapp: HowTo/Deploy/Production.md
        - Find and Connect to Peers:
          - Start a Bootnode: HowTo/Find-and-Connect/Bootnodes.md
          - Configure Ports for Access: HowTo/Find-and-Connect/Configuring-Ports.md
          - Manage Peers: HowTo/Find-and-Connect/Managing-Peers.md
          - Use UPnP: HowTo/Find-and-Connect/Using-UPnP.md
        - Develop on Pantheon:
          - Use Truffle with Pantheon: HowTo/Develop-on-Pantheon/Truffle.md
        - Mine:
          - Configure Mining: HowTo/Mine/Mining.md
        - Troubleshoot:
          - Configure Logging: HowTo/Troubleshoot/Logging.md
          - Solve Common Problems: HowTo/Troubleshoot/Troubleshooting.md
    - Explanation:
        - Architecture: Explanation/ArchitectureOverview.md
        - Consensus Protocols:
          - Overview: Explanation/Consensus-Protocols/Overview-Consensus.md
          - Comparing PoA Consensus Protocols: Explanation/Consensus-Protocols/Comparing-PoA.md
        - Privacy:
          - Overview: Explanation/Privacy/Privacy-Overview.md
          - Privacy Groups: Explanation/Privacy/Privacy-Groups.md
          - Processing Private Transactions: Explanation/Privacy/Private-Transaction-Processing.md
        - Permissioning:
          - Overview: Explanation/Permissioning/Permissioning-Overview.md
          - Onchain Permissioning: Explanation/Permissioning/Onchain-Permissioning.md
        - Transactions:
          - Transaction Pool: Explanation/Transactions/Transaction-Pool.md
          - Vadidating Transactions: Explanation/Transactions/Transaction-Validation.md
        - Events and Logs: Explanation/Events-and-Logs.md
        - Network vs Node Configuration: Explanation/Network-vs-Node.md
        - Network ID and Chain ID: Explanation/NetworkID-And-ChainID.md
        - Node Keys: Explanation/Node-Keys.md
        - Alethio: Explanation/AlethioOverview.md
    - Reference:
        - System Requirements: Reference/System-Requirements.md
        - Pantheon Command Line:
          - Options: Reference/Pantheon-CLI/Pantheon-CLI-Syntax.md
          - Subcommands: Reference/Pantheon-CLI/Pantheon-CLI-Subcommands.md
        - Pantheon API Methods: Reference/Pantheon-API-Methods.md
        - Pantheon API Objects: Reference/Pantheon-API-Objects.md
        - Configuration Items in Genesis File: Reference/Config-Items.md
        - web3.js-eaa Methods: Reference/web3js-eea-Methods.md
        - Accounts for Testing: Reference/Accounts-for-Testing.md
        - Security Disclosure Policy: Reference/Responsible-Disclosure.md
        - Blog Posts and Webinars: Reference/Resources.md

markdown_extensions:
    - toc:
        permalink: 
        toc_depth: 3
    - codehilite
    - markdown_include.include:
        base_path: docs
    - admonition
    - footnotes
    - def_list
    - abbr
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - meta
    - smarty

plugins:
    - search
    - markdownextradata
    - exclude:
        glob:
          - development/*
          - community/*
          - global/*